"""banking module

Revision ID: 2000aef378dc
Revises: 6e759a50554c
Create Date: 2026-07-25 01:51:46.411415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2000aef378dc'
down_revision: Union[str, None] = '6e759a50554c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gl_account_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_iban'), ['iban'], unique=False)

    op.create_table('bank_transactions',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_iban', sa.String(length=34), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UNMATCHED', 'PARTIALLY_MATCHED', 'MATCHED', 'IGNORED', name='banktxstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transactions_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_dedup_key'), ['dedup_key'], unique=False)

    op.create_table('bank_transaction_matches',
    sa.Column('bank_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transaction_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_matches_bank_transaction_id'), ['bank_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_matches_bank_transaction_id'))

    op.drop_table('bank_transaction_matches')
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_company_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_bank_account_id'))

    op.drop_table('bank_transactions')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_iban'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_company_id'))

    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
