"""fixed assets

Revision ID: 28456dc2c747
Revises: 2000aef378dc
Create Date: 2026-07-25 02:14:27.155930
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28456dc2c747'
down_revision: Union[str, None] = '2000aef378dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('in_service_date', sa.Date(), nullable=False),
    sa.Column('initial_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('STRAIGHT_LINE', name='depreciationmethod', native_enum=False, length=20), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISPOSED', 'WRITTEN_OFF', name='assetstatus', native_enum=False, length=20), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('gl_asset_account_id', sa.Uuid(), nullable=True),
    sa.Column('gl_expense_account_id', sa.Uuid(), nullable=True),
    sa.Column('gl_accum_account_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gl_accum_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gl_asset_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gl_expense_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'inventory_number', name='uq_asset_company_invno')
    )
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_assets_company_id'), ['company_id'], unique=False)

    op.create_table('depreciation_entries',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'year', 'month', name='uq_depr_asset_period')
    )
    with op.batch_alter_table('depreciation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depreciation_entries_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depreciation_entries_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depreciation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depreciation_entries_company_id'))
        batch_op.drop_index(batch_op.f('ix_depreciation_entries_asset_id'))

    op.drop_table('depreciation_entries')
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_assets_company_id'))

    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
