"""invoice original ref

Revision ID: 3b82295f4da8
Revises: 499ff0b44f28
Create Date: 2026-07-25 03:59:50.651009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b82295f4da8'
down_revision: Union[str, None] = '499ff0b44f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_invoice_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'invoices', ['original_invoice_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_invoice_id')

    # ### end Alembic commands ###
