"""purchase invoices

Revision ID: 499ff0b44f28
Revises: 4e44ac449030
Create Date: 2026-07-25 03:06:01.756674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '499ff0b44f28'
down_revision: Union[str, None] = '4e44ac449030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_invoices',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_document_number', sa.String(length=50), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('tax_event_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_code_id', sa.Uuid(), nullable=True),
    sa.Column('expense_account_id', sa.Uuid(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='purchasestatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('vat_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vat_code_id'], ['vat_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vat_entry_id'], ['vat_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_counterparty_id'), ['counterparty_id'], unique=False)

    op.create_table('purchase_invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_lines_invoice_id'))

    op.drop_table('purchase_invoice_lines')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_counterparty_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_company_id'))

    op.drop_table('purchase_invoices')
    # ### end Alembic commands ###
