"""payments

Revision ID: 4e44ac449030
Revises: b7b29bff51a2
Create Date: 2026-07-25 02:42:03.152668
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e44ac449030'
down_revision: Union[str, None] = 'b7b29bff51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proposals',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_iban', sa.String(length=34), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PREPARED', 'APPROVED', 'REJECTED', 'CANCELLED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('prepared_by_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_proposals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_proposals_counterparty_id'), ['counterparty_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_proposals_counterparty_id'))
        batch_op.drop_index(batch_op.f('ix_payment_proposals_company_id'))

    op.drop_table('payment_proposals')
    # ### end Alembic commands ###
