"""initial schema

Revision ID: 6e759a50554c
Revises: 
Create Date: 2026-07-25 01:42:58.521190
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e759a50554c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('eik', sa.String(length=20), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_eik'), ['eik'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_vat_number'), ['vat_number'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', 'OFF_BALANCE', name='accounttype', native_enum=False, length=20), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_account_company_code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('fiscal_years',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_fiscal_year_company_year')
    )
    with op.batch_alter_table('fiscal_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_years_company_id'), ['company_id'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'CFO', 'CHIEF_ACCOUNTANT', 'ACCOUNTANT', 'EXTERNAL_ACCOUNTANT', 'AUDITOR', 'TAX_CONSULTANT', 'EMPLOYEE_SUBMITTER', 'EMPLOYEE_APPROVER', 'SYS_ADMIN', 'SECURITY_ADMIN', 'READ_ONLY', name='companyrole', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_membership_user_company')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('vat_codes',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('SALE', 'PURCHASE', name='vatdirection', native_enum=False, length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gives_credit', sa.Boolean(), nullable=False),
    sa.Column('requires_vies', sa.Boolean(), nullable=False),
    sa.Column('requires_protocol', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_vat_code_company_code')
    )
    with op.batch_alter_table('vat_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_codes_company_id'), ['company_id'], unique=False)

    op.create_table('accounting_periods',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_year_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'CLOSING', 'CLOSED', 'LOCKED', name='periodstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_period_company_code')
    )
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_periods_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_periods_fiscal_year_id'), ['fiscal_year_id'], unique=False)

    op.create_table('counterparties',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'SUPPLIER', 'BOTH', name='counterpartytype', native_enum=False, length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('eik', sa.String(length=20), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('default_account_id', sa.Uuid(), nullable=True),
    sa.Column('default_vat_code_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_vat_code_id'], ['vat_codes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparties_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparties_eik'), ['eik'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparties_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparties_vat_number'), ['vat_number'], unique=False)

    op.create_table('counterparty_bank_accounts',
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparty_bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_bank_accounts_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_bank_accounts_iban'), ['iban'], unique=False)

    op.create_table('journal_entries',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('entry_number', sa.Integer(), nullable=True),
    sa.Column('journal', sa.Enum('GENERAL', 'SALES', 'PURCHASES', 'CASH', 'BANK', 'FIXED_ASSETS', 'DEPRECIATION', 'FX', 'PAYROLL', 'CLOSING', 'OPENING', name='journaltype', native_enum=False, length=20), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('tax_event_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', 'REVERSAL', name='entrystatus', native_enum=False, length=20), nullable=False),
    sa.Column('reverses_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('posted_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['journal_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'entry_number', name='uq_entry_company_number')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_period_id'), ['period_id'], unique=False)

    op.create_table('documents',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.Enum('UNKNOWN', 'INVOICE_PURCHASE', 'INVOICE_SALE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'RECEIPT', 'BANK_STATEMENT', 'CONTRACT', 'OTHER', name='documenttype', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'EMAIL', 'MOBILE', 'API', 'INTEGRATION', name='documentsource', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'OCR_PROCESSING', 'RECOGNIZED', 'NEEDS_REVIEW', 'MISSING_DATA', 'POTENTIAL_DUPLICATE', 'PROPOSED', 'RETURNED', 'APPROVED', 'POSTED', 'ARCHIVED', 'CANCELLED', name='documentstatus', native_enum=False, length=25), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('journal_lines',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('debit_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_entry_id'), ['entry_id'], unique=False)

    op.create_table('vat_entries',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('vat_code_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('SALE', 'PURCHASE', name='vatdirection', native_enum=False, length=10), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('tax_event_date', sa.Date(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_vat_number', sa.String(length=20), nullable=True),
    sa.Column('tax_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vat_code_id'], ['vat_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vat_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_entries_period_id'), ['period_id'], unique=False)

    op.create_table('document_extractions',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extractions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extractions_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_company_id'))

    op.drop_table('document_extractions')
    with op.batch_alter_table('vat_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_entries_period_id'))
        batch_op.drop_index(batch_op.f('ix_vat_entries_company_id'))

    op.drop_table('vat_entries')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_period_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_company_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('counterparty_bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_bank_accounts_iban'))
        batch_op.drop_index(batch_op.f('ix_counterparty_bank_accounts_counterparty_id'))

    op.drop_table('counterparty_bank_accounts')
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparties_vat_number'))
        batch_op.drop_index(batch_op.f('ix_counterparties_name'))
        batch_op.drop_index(batch_op.f('ix_counterparties_eik'))
        batch_op.drop_index(batch_op.f('ix_counterparties_company_id'))

    op.drop_table('counterparties')
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_periods_fiscal_year_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_periods_company_id'))

    op.drop_table('accounting_periods')
    with op.batch_alter_table('vat_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_codes_company_id'))
        batch_op.drop_index(batch_op.f('ix_vat_codes_code'))

    op.drop_table('vat_codes')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_company_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('fiscal_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_years_company_id'))

    op.drop_table('fiscal_years')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_company_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_code'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_vat_number'))
        batch_op.drop_index(batch_op.f('ix_companies_eik'))

    op.drop_table('companies')
    # ### end Alembic commands ###
